### ISSUE TITLE
How to use it to calculate tps cofficients between source and target image?

### ISSUE THREAD

**Issue by KakaVlasic** [tzing/tps-deformation#1]
I don't know how to use it,can you explain it carefully?Thanks

**Comment by tzing** [comment]
hi, I've add an example on readme
hope this helps :)

**Comment by KakaVlasic** [comment]
thank you very much！
 I successfuly run your example and I couldn’t find coefficient variable in trans("trans" is not in Variable list ),can I visualize the cofficient? thanks again!

# get coefficient, use class
trans = tps.TPS(source_xy, deform_xy)

**Comment by tzing** [comment]
oops, i misunderstand your question.

 `trans` is a class that stored the coefficient and control points which is needed on perform transformation.
if you just want to get the coefficenet, it's in `trans.coefficient`.
but it would be hard to visuallize, since they are high dimensional vectors.

**Comment by KakaVlasic** [comment]
so cool! thank you for you generous help!
